---
title: Enkota
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
  uploads:
    title: Uploads
    output: true
email: scott@enkota.com
description: WordPress Design & Development - Audio Mixing/Mastering Services
baseurl: ''
url: ''
twitter_username: scopeak
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
